AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  apple-checker

  Sample SAM Template for apple-checker

Resources:
  ProductAvailStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: src/statemachine/product-avail.asl.json
      DefinitionSubstitutions:
        ProductAvailCheckerFunctionArn: !GetAtt ProductAvailCheckerFunction.Arn
        DiscordPublisherFunctionArn: !GetAtt DiscordPublisherFunction.Arn
        DDBGetItem: !Sub arn:${AWS::Partition}:states:::dynamodb:getItem
        DDBPutItem: !Sub arn:${AWS::Partition}:states:::dynamodb:putItem
        DDBProductAvail: !Ref ProductAvailTable
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref ProductAvailCheckerFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref DiscordPublisherFunction
        - DynamoDBReadPolicy:
            TableName: !Ref ProductAvailTable
        - DynamoDBWritePolicy:
            TableName: !Ref ProductAvailTable

  ProductAvailCheckerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/product-avail-checker/
      Handler: app.handler
      Runtime: nodejs14.x
      MemorySize: 512
      Timeout: 10

  DiscordPublisherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/discord-publisher/
      Handler: app.handler
      Runtime: nodejs14.x
      MemorySize: 512
      Timeout: 10
      Environment:
        Variables:
          ENV: prod


  ProductAvailTable:
    Type: AWS::Serverless::SimpleTable # More info about SimpleTable Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-simpletable.html
    Properties:
      PrimaryKey:
        Name: url
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
        

Outputs:
  ProductAvailStateMachine:
    Description: "ProductAvailStateMachine ARN"
    Value: !Ref ProductAvailStateMachine
  ProductAvailStateMachineRole:
    Description: "ProductAvailStateMachine IAM Role"
    Value: !GetAtt ProductAvailStateMachineRole.Arn
